name: instagramclone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_core: ^0.4.4
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  cloud_firestore: ^0.13.6
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.0
  email_validator: ^1.0.4
  password_strength: ^0.1.2
  built_value: ^7.1.0
  built_collection: ^4.3.2
  camera: ^0.5.7+4
  path_provider: ^1.6.7
  uuid: ^2.0.4
  firebase_storage: ^3.1.6
  redux_epics: ^0.13.0
  rxdart: ^0.24.0
  algolia: ^0.1.7


dependency_overrides:
  rxdart: ^0.24.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true

  assets:
    - res/instalogo.png
